AcceptedMsg: '&2You have succesfully accepted the &6rules&2! Have fun!'
MustReadRules: '&4You must read the &6rules &4in order to accept them!'
AcceptedAllreadyMsg: '&4You have allready accepted the &6rules&4!'
CantBuildMsg: '&4You must accept &6rules &4to build!'
InformMsg: '&2You have to accept the &6rules&2! Use &3/rules &2and then &3/acceptrules&2!'
RulesCmd: '/rules'
BuiltInRulesManager: true
TpAfterAccept: true
InformUser: true
NotifyOPs: true
TpOnJoin: false
AllowBuildBeforeAccept: false
AllowMoveBeforeAccept: true
BlockCommandsBeforeAccept: true
TpWorld: world
TpPositionX: 0
TpPositionY: 0
TpPositionZ: 0
TpPositionPitch: 0
TpPositionYaw: 0
SpawnWorld: world
SpawnPositionX: 0
SpawnPositionY: 0
SpawnPositionZ: 0
SpawnPositionPitch: 0
SpawnPositionYaw: 0